Q.1 Write a program to create a NumPy 1D-array with 5 elements and perform basic 
operations like: 
a) Addition of 2 in all the element  
b) Multiply 3 with all the elements 
c) Divide every element by 2 

In [1]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print("Original array:", arr)

print("After adding 2:", arr + 2)

print("After multiplying by 3:", arr * 3)

print("After dividing by 2:", arr / 2)

Original array: [10 20 30 40 50]
After adding 2: [12 22 32 42 52]
After multiplying by 3: [ 30  60  90 120 150]
After dividing by 2: [ 5. 10. 15. 20. 25.]


Q.2 Questions on Basic NumPy Array: 
a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5]) 
b) Find the most frequent value and their indice(s) in the following arrays: 
i. x = np.array([1,2,3,4,5,1,2,1,1,1]) 
ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [2]:
import numpy as np

arr = np.array([1, 2, 3, 6, 4, 5])

print("(a) Original array:", arr)
print("(a) Reversed array:", arr[::-1])

x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])

values, counts = np.unique(x, return_counts=True)
max_count = np.max(counts)
most_frequent = values[counts == max_count]

print("\n(b)(i) Most frequent value:", most_frequent)
print("Frequency:", max_count)

for value in most_frequent:
    print("Indices of", value, ":", np.where(x == value)[0])

y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

values, counts = np.unique(y, return_counts=True)
max_count = np.max(counts)
most_frequent = values[counts == max_count]

print("\n(b)(ii) Most frequent values:", most_frequent)
print("Frequency:", max_count)

for value in most_frequent:
    print("Indices of", value, ":", np.where(y == value)[0])

(a) Original array: [1 2 3 6 4 5]
(a) Reversed array: [5 4 6 3 2 1]

(b)(i) Most frequent value: [1]
Frequency: 5
Indices of 1 : [0 5 7 8 9]

(b)(ii) Most frequent values: [1 3]
Frequency: 3
Indices of 1 : [0 1 2]
Indices of 3 : [4 8 9]


Q.3 For the given 2-D array arr=np.array([10, 20, 30], [40, 50, 60], [70, 80, 90]), access 
elements using row and column indices as follows: 
a) Access 1st row, 2nd column  
b) Access 3rd row, 1st column 

In [3]:
import numpy as np

arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print("(a) 1st row, 2nd column:", arr[0, 1])

print("(b) 3rd row, 1st column:", arr[2, 0])

(a) 1st row, 2nd column: 20
(b) 3rd row, 1st column: 70


Q.4 Write program to create an 1-D NumPy array named <<Your Name>> with evenly 
spaced 25 numbers from 10 to 100 using linspace(). Print the dimensions of the array, 
shape, total elements, the data type of each element and total number of bytes consumed 
by the array. Find the transpose of this array using reshape() attribute. Can we do the same 
with T attribute? 

In [4]:
import numpy as np

Tanishq = np.linspace(10, 100, 25)

print("Array:")
print(Tanishq)

print("\nDimensions:", Tanishq.ndim)
print("Shape:", Tanishq.shape)
print("Total elements:", Tanishq.size)
print("Data type:", Tanishq.dtype)
print("Total bytes:", Tanishq.nbytes)

transpose = Tanishq.reshape(1, 25)

print("\nTranspose using reshape():")
print(transpose.T)

print("\nUsing T attribute:")
print(transpose.T)

print("\nCan transpose be done using T attribute?")
print("Yes, but a 1-D array's .T does not change its shape.")
print("Therefore, reshape(1, 25).T is used to get a 25 x 1 transpose.")

Array:
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]

Dimensions: 1
Shape: (25,)
Total elements: 25
Data type: float64
Total bytes: 200

Transpose using reshape():
[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]

Using T attribute:
[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]

Can transpose be done using T attribute?
Yes, but a 1-D array's .T does not change its shape.
Therefore, reshape(1, 25).T is used to get a 25 x 1 transpose.


Q5. Create a 2-D Array of three rows and four columns, named ucs420_<your_name>> 
with following values – 10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35. Compute the mean, 
median, max, min, unique elements. Reshape the array to four rows and three columns and 
name it as reshaped_ ucs420_<your_name>>. Resize the array to two rows and three 
columns and name it as resized_ ucs420_<your_name>>.

In [5]:
import numpy as np

ucs420_Tanishq = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 15, 20, 35]
])

print("Original array:")
print(ucs420_Tanishq)

print("\nMean:", np.mean(ucs420_Tanishq))
print("Median:", np.median(ucs420_Tanishq))
print("Maximum:", np.max(ucs420_Tanishq))
print("Minimum:", np.min(ucs420_Tanishq))
print("Unique elements:", np.unique(ucs420_Tanishq))

reshaped_ucs420_Tanishq = ucs420_Tanishq.reshape(4, 3)

print("\nReshaped array (4 x 3):")
print(reshaped_ucs420_Tanishq)

resized_ucs420_Tanishq = np.resize(ucs420_Tanishq, (2, 3))

print("\nResized array (2 x 3):")
print(resized_ucs420_Tanishq)

Original array:
[[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]

Mean: 43.333333333333336
Median: 37.5
Maximum: 90
Minimum: 10
Unique elements: [10 15 20 30 35 40 50 60 70 80 90]

Reshaped array (4 x 3):
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]

Resized array (2 x 3):
[[10 20 30]
 [40 50 60]]
